### PR TITLE
initial rock paper scissors implementation

### PR DESCRIPTION
**Pull request by trbs**
a multi player rock-paper-scissors transaction family.

based on xo, pretty unpolished and missing parts to nicely visualize the game.

### CODE REVIEW

**Comment by trbs** [comment]
just wanted to put it out there.

**Comment by vaporos** [comment]
Awesome!

**Comment by vaporos** [comment]
@trbs, can you submit a PR which includes copyright headers to keep the licensing clear?

Thanks!

**Comment by trbs** [comment]
@vaporos created https://github.com/hyperledger/sawtooth-arcade/pull/8 which adds the copyright headers and sawtooth_rps to the readme.

**Pull request merged**
